name: Create Go Release (Linux)

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Change directory
      run: cd $GITHUB_WORKSPACE

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'

    - name: Build
      run: go build -v ./

    - name: Test
      run: go test -v ./

    - name: Publish Release
      uses: softprops/action-gh-release@v1
      id: create_release
      with:
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: true
        files: |
          ./${{ github.event.repository.name }}
